site_name: Skel learn mkdocs
site_url: https://example.com/

nav: 
    - Introduction: 'index.md'
    - Examples: 'tables.md'
    - Code Example: 'code/example_c.html'

theme:
    name: readthedocs

plugins: []
